<?php

namespace App\Filament\Widgets;

use Carbon\Carbon;
use Filament\Widgets\ChartWidget;
use Illuminate\Support\Facades\DB;

class ReservationsTimeSeries extends ChartWidget
{
    protected ?string $heading = 'Visitors per day';

    // Optioneel: refresh elke 60s (default is 5s)
    protected ?string $pollingInterval = '60s';

    public ?string $from = null;
    public ?string $to = null;

    protected $listeners = [
        'analyticsRangeUpdated' => 'setRange'
    ];

    public function setRange(String $from, String $to): void
    {
        $this->from = $from;
        $this->to = $to;
        $this->dispatch('$refresh');
    }
    protected int|string|array $columnSpan = 2;

    protected function getMaxHeight(): ?string
    {
        return '500 px'; // TODO: Change the autogenerated stub
    }

    protected function getType(): string
    {
        return 'line';
    }

    protected function getOptions(): array
    {
        return[
            'scales' => [
                'y' => [
                    'ticks' => [
                        'precision' => 0,
                        'stepSize' => 1,
                    ],
                    'beginAtZero' => true,
                ],
            ],
        ];
    }
    protected function getData(): array
    {
        $from = $this->from ?? now()->subDays(5)->toDateString();
        $to   = $this->to   ?? now()->addDays(31)->toDateString();

        $rows = DB::select(
            "
            WITH RECURSIVE dates AS (
              SELECT CAST(? AS DATE) AS day
              UNION ALL
              SELECT DATE_ADD(day, INTERVAL 1 DAY)
              FROM dates
              WHERE day < CAST(? AS DATE)
            )
            SELECT
              d.day,
              COALESCE(COUNT(v.id), 0) AS visitor_count
            FROM dates d
            LEFT JOIN reservations r
              ON r.date = d.day
              AND r.status = 'confirmed'
            LEFT JOIN visitors v
              ON v.reservation_id = r.id
            GROUP BY d.day
            ORDER BY d.day;
            ",
            [$from, $to]
        );

        $labels = [];
        $data = [];

        foreach ($rows as $row) {
            $labels[] = Carbon::parse($row->day)->format('d M'); // bv "23 Jan"
            $data[]   = (int) $row->visitor_count;
        }

        return [
            'datasets' => [
                [
                    'label' => 'Visitors',
                    'data' => $data,
                    // Je kan Chart.js opties toevoegen als je wil
                ],
            ],
            'labels' => $labels,
        ];
    }
}
